apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: neo4j-core
  namespace: ${ptnamespace}
spec:
  serviceName: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
        component: core
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - neo4j
            topologyKey: kubernetes.io/hostname
      containers:
      - name: neo4j
        #image: "neo4j:3.5-enterprise"
        image: "neo4j:3.5.5-enterprise"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: NEO4J_AUTH
            value: neo4j/pentium
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
        ports:
        - containerPort: 7474
          name: browser
        - containerPort: 7687
          name: bolt
        securityContext:
          privileged: true
        volumeMounts:
        - name: datadir
          mountPath: "/data"
        - name: logdir
          mountPath: "/logs"
        - name: import
          mountPath: "/var/lib/neo4j/import"
        - name: plugin
          mountPath: "/plugins"
        #- name: config
        #  mountPath: "/var/lib/neo4j/conf/neo4j.conf"
        #  subPath: neo4j.conf
        #  readOnly: false
      volumes:
       - name: datadir
         hostPath:
           path: ${NEO4JDIR}/${ptnamespace}
       - name: logdir
         hostPath:
           path: ${NEO4JDIR}/logs/${ptnamespace}
       - name: import
         hostPath:
           path: ${NEO4JDIR}/import/${ptnamespace}
       - name: plugin
         hostPath:
           path: ${NEO4JDIR}/plugin/${ptnamespace}
       #- name: config
       #  configMap:
       #     name: neo4j-config
            #items:
            #- key: neo4j.conf
            #  path: neo4j.conf
            #optional: true
      nodeSelector:
        ptnodetype: "datanode"
#  volumeClaimTemplates:
#    - metadata:
#        name: datadir
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        storageClassName: "standard"
#        resources:
#          requests:
#            storage: "10Gi"
